=== BlueBeastMight/qprc/qrpc-framework/qrpc-core/src/main/java/icu/chiou/builder/xml/qrpc-config.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT configuration ANY>


        <!ELEMENT port ANY>
        <!ELEMENT application ANY>

        <!ELEMENT registry EMPTY>
        <!ATTLIST registry
                url CDATA #REQUIRED
                >

        <!ELEMENT serializer EMPTY>
        <!ATTLIST serializer
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                class CDATA #REQUIRED
                >
        <!ELEMENT serializeType EMPTY>
        <!ATTLIST serializeType
                type CDATA #REQUIRED
                >

        <!ELEMENT compressor EMPTY>
        <!ATTLIST compressor
                code CDATA #REQUIRED
                name CDATA #REQUIRED
                class CDATA #REQUIRED
                >
        <!ELEMENT compressType EMPTY>
        <!ATTLIST compressType
                type CDATA #REQUIRED
                >

        <!ELEMENT loadBalancer EMPTY>
        <!ATTLIST loadBalancer
                class CDATA #REQUIRED
                >
        <!ELEMENT loadBalancerType EMPTY>
        <!ATTLIST loadBalancerType
                type CDATA #REQUIRED
                >

        <!ELEMENT idGenerator EMPTY>
        <!ATTLIST idGenerator
                class CDATA #REQUIRED
                dataCenterId CDATA #REQUIRED
                MachineId CDATA #REQUIRED
                >

=== BlueBeastMight/qprc/qrpc-framework/qrpc-core/src/main/resources/qrpc.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration SYSTEM "qrpc-config.dtd">
<configuration>
    <!--端口号-->
    <port>8093</port>

    <!--应用名-->
    <application>qrpc-default-applicationName</application>

    <!--注册中心-->
    <registry url="zookeeper://127.0.0.1:2181"/>

    <!-- 二选一 -->
    <!--序列化协议-->
    <serializeType type="hessian"/>
    <serializer code="1" name="hessian" class="icu.chiou.serialize.wrapper.impl.HessianSerializer"/>

    <!-- 二选一 -->
    <!--压缩协议-->
    <compressType type="gzip"/>
    <compressor code="1" name="gzip" class="icu.chiou.compress.wrapper.impl.GzipCompressor"/>

    <!-- 二选一 -->
    <!--负载均衡策略-->
    <loadBalancer class="icu.chiou.loadbalancer.impl.MinimumResponseTimeLoadBalancer"/>
    <loadBalancerType type="minimumResponseTime"/>

    <!--id生成器-->
    <idGenerator class="icu.chiou.IDGenerator" dataCenterId="2" MachineId="4"/>
</configuration>
